Repository computingfuturetech/officeERP, pull requests merged in 2025-02, with the labels that each got.

#85 OE-15 | Backend | Code Refactor | Database Optimization | MAIN_AND_SUB_HEAD_OF_ACCOUNT
  serverside/index.js
  serverside/src/controllers/expenseHeadOfAccountController/createMainHeadOfAccount.js
  serverside/src/controllers/expenseHeadOfAccountController/createSubHeadOfAccount.js
  serverside/src/controllers/expenseHeadOfAccountController/headOfAccount.js
  serverside/src/controllers/expenseHeadOfAccountController/listOfHeadOfAccount.js
  serverside/src/models/expenseModel/expenseHeadOfAccount/mainHeadOfAccount.js
  serverside/src/routes/coreRoutes/expenseApi.js
  serverside/src/routes/expenseHeadOfAccountRoutes/expenseHeadOfAccount.js
Labels: enhancement, bug fix

#87 OE-17 | Backend | Code Refactor | Database Optimization | OFFICE_UTILITY_EXPENSE
  serverside/index.js
  serverside/src/controllers/expenseController/officeUtilExpense.js
  serverside/src/models/expenseModel/officeUtilExpense/officeutilExpense.js
  serverside/src/routes/officeUtilExpenseRoutes/officeUtilExpense.js
Labels: enhancement, bug fix

#88 OE-14 | Frontend Transfer Income
  officeErpFrontend/src/components/components/app-sidebar.tsx
  officeErpFrontend/src/components/components/dynamic-sheet.tsx
  officeErpFrontend/src/routes/routes.jsx
  officeErpFrontend/src/services/transferIncome.js
  officeErpFrontend/src/views/TransferIncome/index.jsx
  officeErpFrontend/src/views/index.jsx
  officeErpFrontend/tsconfig.json
Labels: enhancement, feature

#89 OE-19 | Frontend | Office Expense
  officeErpFrontend/index.html
  officeErpFrontend/manifest.json
  officeErpFrontend/service-worker.js
  officeErpFrontend/src/components/DisableNumberScroll/index.jsx
  officeErpFrontend/src/components/components/app-sidebar.tsx
  officeErpFrontend/src/components/components/dynamic-sheet.tsx
  officeErpFrontend/src/index.jsx
  officeErpFrontend/src/index.scss
  officeErpFrontend/src/routes/routes.jsx
  officeErpFrontend/src/services/officeExpense.js
  officeErpFrontend/src/views/OfficeExpense/index.jsx
  officeErpFrontend/src/views/index.jsx
Labels: feature

#90 OE-18 | Backend | Code Refactor | Database Optimization | SALARY_EXPENSE and Office Expense
  serverside/index.js
  serverside/src/controllers/expenseController/auditExpense.js
  serverside/src/controllers/expenseController/bankChargesExpense.js
  serverside/src/controllers/expenseController/getAllExpense.js
  serverside/src/controllers/expenseController/legalProfessionalExpense.js
  serverside/src/controllers/expenseController/miscellaneousExpense.js
  serverside/src/controllers/expenseController/officeExpense.js
  serverside/src/controllers/expenseController/officeUtilExpense.js
  serverside/src/controllers/expenseController/salaries.js
  serverside/src/controllers/expenseController/salaryType.js
  serverside/src/controllers/expenseHeadOfAccountController/headOfAccount.js
  serverside/src/models/expenseModel/bankChargesExpense/bankChargesExpense.js
  serverside/src/models/expenseModel/legalProfessionalExpense/legalProfessionalExpense.js
  serverside/src/models/expenseModel/miscellaneousExpense/miscellaneousExpense.js
  serverside/src/models/expenseModel/officeExpense/officeExpense.js
  serverside/src/models/expenseModel/salaries/salaries.js
  serverside/src/routes/legalProfessionalExpenseRoutes/legalProfessionalExpense.js
  serverside/src/routes/miscellaneousExpenseRoutes/miscellaneousExpense.js
  serverside/src/routes/officeExpenseRoutes/officeExpense.js
  serverside/src/routes/salaryRoutes/salary.js
Labels: enhancement, bug fix

#91 OE-19 | Frontend Office Expense bug fix
  officeErpFrontend/src/components/components/data-table.tsx
  officeErpFrontend/src/components/components/dynamic-sheet.tsx
  officeErpFrontend/src/components/components/ui/sheet.tsx
  officeErpFrontend/src/components/components/ui/textarea.tsx
  officeErpFrontend/src/views/OfficeExpense/index.jsx
Labels: enhancement, bug fix

#92 OE-18 | Backend | Code Refactor | Database Optimization | SALARY_EXPENSE | Bank charges expense bugfix
  serverside/src/controllers/expenseController/bankChargesExpense.js
  serverside/src/controllers/expenseHeadOfAccountController/headOfAccount.js
  serverside/src/models/expenseModel/bankChargesExpense/bankChargesExpense.js
Labels: bug fix

#95 OE-22 | Frontend Reports
  officeErpFrontend/src/components/components/app-sidebar.tsx
  officeErpFrontend/src/routes/routes.jsx
  officeErpFrontend/src/views/Reports/index.jsx
  officeErpFrontend/src/views/index.jsx
Labels: feature

#96 OE-3 | Backend | Code Refactor | Database Optimization | BANK_LIST an…
  serverside/src/controllers/bankController/bankBalance.js
Labels: enhancement, bug fix

#97 OE-24 | Frontend Script Executor
  officeErpFrontend/package-lock.json
  officeErpFrontend/package.json
  officeErpFrontend/src/components/components/ui/tabs.tsx
  officeErpFrontend/src/routes/routes.jsx
  officeErpFrontend/src/views/ApiTester/index.jsx
  officeErpFrontend/src/views/index.jsx
Labels: feature

#98 OE-23 | Backend Code Refactor Bank Legder | Pdf Creation
  serverside/bankLedgerPdf.pdf
  serverside/index.js
  serverside/package-lock.json
  serverside/package.json
  serverside/src/controllers/templateController/bankLedgerPdf.js
  serverside/src/middleware/checkBank.js
  serverside/src/middleware/createBankLedger.js
  serverside/src/routes/coreRoutes/coreApi.js
  serverside/src/routes/pdfRoutes/pdf.js
  serverside/src/utils/generatePdf.js
  serverside/src/utils/getLedgerDetailHtml.js
  serverside/src/utils/getLedgerTableHtml.js
  serverside/src/views/ledgerTemplate.html
Labels: bug fix

#100 OE-3 | Backend | Code Refactor | Database Optimization | BANK_LIST | Bug Fix
  serverside/src/controllers/bankController/bank.js
  serverside/src/models/bankModel/bank.js
  serverside/src/routes/bankRoutes/bank.js
Labels: enhancement, bug fix

#102 OE-26 | Backend Code Refactor Cash And General Legder | Pdf Creation | Bug Fix
  serverside/src/controllers/templateController/bankLedgerPdf.js
  serverside/src/controllers/templateController/cashLedgerPdf.js
  serverside/src/controllers/templateController/generalLedgerPdf.js
  serverside/src/utils/getLedgerDetailHtml.js
Labels: bug fix

#103 OE-28 | Frontend | Fixed Amount
  officeErpFrontend/src/components/components/app-sidebar.tsx
  officeErpFrontend/src/routes/routes.jsx
  officeErpFrontend/src/services/fixedAmount.js
  officeErpFrontend/src/views/FixedAmount/index.jsx
  officeErpFrontend/src/views/index.jsx
Labels: feature

#104 OE-27 | Backend | Code Refactor | Database Optimization | FIXED_AMOUNT
  serverside/index.js
  serverside/src/controllers/fixedAmountController/fixedAmount.js
  serverside/src/models/fixedAmountModel/fixedAmount.js
  serverside/src/routes/coreRoutes/coreApi.js
  serverside/src/routes/coreRoutes/fixedAmountApi.js
  serverside/src/routes/fixedAmountRoutes/fixedAmount.js
Labels: enhancement, bug fix

#105 OE-26 | Backend Code Refactore Cash And General Ledger | Bug Fix
  serverside/src/controllers/templateController/bankLedgerPdf.js
  serverside/src/controllers/templateController/cashLedgerPdf.js
  serverside/src/controllers/templateController/generalLedgerPdf.js
  serverside/src/middleware/createBankLedger.js
  serverside/src/middleware/createCashBookLedger.js
  serverside/src/middleware/createGeneralLedger.js
  serverside/src/utils/getLedgerTableHtml.js
  serverside/src/views/ledgerTemplate.html
Labels: bug fix

#108 OE-13 | Backend | Code Refactor | Database Optimization | SELLER_PURCHASES_INCOME | BUG_FIX
  serverside/src/controllers/incomeController/sellerPurchaseIncome.js
  serverside/src/models/incomeModels/sellerPurchaseIncome/sellerPurchaseIncome.js
Labels: bug fix

#106 OE-14 | Frontend Transfer Income | paid date readonly in edit mode
  officeErpFrontend/src/views/BankProfit/index.jsx
  officeErpFrontend/src/views/OfficeExpense/index.jsx
  officeErpFrontend/src/views/SiteExpense/index.jsx
  officeErpFrontend/src/views/TransferIncome/index.jsx
Labels: enhancement, bug fix

#111 OE-30 | Backend | Code Refactor | Database Optimization | BALANCE_SHEET | Made Balance Sheet and Income Record Year Specified
  serverside/src/controllers/templateController/balanceSheet.js
  serverside/src/controllers/templateController/bankLedgerPdf.js
  serverside/src/controllers/templateController/cashLedgerPdf.js
  serverside/src/controllers/templateController/generalLedgerPdf.js
  serverside/src/controllers/templateController/incomeRecord.js
  serverside/src/routes/reportRoutes/report.js
Labels: bug fix

#112 OE-22 | Frontend Reports bank cash general report
  officeErpFrontend/src/services/banks.js
  officeErpFrontend/src/services/reports.js
  officeErpFrontend/src/views/Reports/index.jsx
Labels: feature

#114 OE-22 | Frontend Reports integration
  officeErpFrontend/src/services/reports.js
  officeErpFrontend/src/views/Reports/index.jsx
Labels: enhancement, feature

#113 OE-31 | Backend Code Refactor Permissions
  serverside/src/config/userPermissions.js
  serverside/src/controllers/userController/login.js
Labels: feature

#115 OE-32 | Frontend Role Based Permissions
  officeErpFrontend/src/components/components/app-sidebar.tsx
  officeErpFrontend/src/components/components/protected-route.tsx
  officeErpFrontend/src/redux/user/user.js
  officeErpFrontend/src/routes/routes.jsx
Labels: feature

#117 OE-33 | Frontend Dashboard Integrations
  officeErpFrontend/src/components/components/data-table.tsx
  officeErpFrontend/src/views/Home/index.jsx
Labels: enhancement

#118 OE-1 | Backend Code | Refactor | Get Users API
  serverside/index.js
  serverside/src/config/config.js
  serverside/src/controllers/userController/create.js
  serverside/src/controllers/userController/getUsers.js
  serverside/src/routes/coreRoutes/coreApi.js
Labels: feature

#122 OE-1 | Backend Code Refactor
  serverside/balanceSheet.pdf
  serverside/bankLedgerPdf.pdf
  serverside/cashLedgerPdf.pdf
  serverside/generalLedgerPdf.pdf
  serverside/incomeAndExpenseRecord.pdf
  serverside/incomeRecordPdf.pdf
  serverside/src/controllers/expenseController/auditExpense.js
  serverside/src/controllers/expenseController/bankChargesExpense.js
  serverside/src/controllers/expenseController/electricityAndWaterConnectionExpense.js
  serverside/src/controllers/expenseController/legalProfessionalExpense.js
  serverside/src/controllers/expenseController/miscellaneousExpense.js
  serverside/src/controllers/expenseController/officeExpense.js
  serverside/src/controllers/expenseController/officeUtilExpense.js
  serverside/src/controllers/expenseController/salaries.js
  serverside/src/controllers/expenseController/siteExpense.js
  serverside/src/controllers/expenseController/vehicleDisposalExpense.js
  serverside/src/controllers/incomeController/bankProfit.js
  serverside/src/controllers/incomeController/possessionFee.js
  serverside/src/controllers/incomeController/sellerPurchaseIncome.js
  serverside/src/controllers/incomeController/waterMaintenanceBill.js
  serverside/src/controllers/incomeStatementController/incomeStatement.js
  serverside/src/controllers/operatingFixedAssetsController/operatingFixedAssets.js
  serverside/src/controllers/payableVoucherController/createPayableVoucher.js
  serverside/src/controllers/templateController/bankLedgerPdf.js
  serverside/src/controllers/templateController/threeTierChallan.js
  serverside/src/controllers/userController/create.js
  serverside/src/controllers/userController/forgetPassword.js
  serverside/src/controllers/userController/login.js
  serverside/src/controllers/userController/newPasswordSet.js
  serverside/src/controllers/userController/otpVerify.js
  serverside/src/controllers/userController/updateUser.js
  serverside/src/models/coreModels/Admin.js
  serverside/src/models/coreModels/forgetPassword.js
  serverside/src/models/headOfAccountModel/headOfAccount.js
  serverside/src/models/incomeModels/incomeHeadOfAccount/typeOfHeadOfAccount.js
  serverside/src/models/incomeModels/pssessionFeeModel/possessionFee.js
  serverside/src/models/incomeStatementModel/incomeStatement.js
  serverside/src/models/liabilitiesModel/currentLiabilities.js
  serverside/src/models/operatingFixedAssetsModels/operatingFixedAssets.js
  serverside/src/models/payableVoucherModel/payableVouchers.js
  serverside/src/routes/coreRoutes/coreApi.js
  serverside/src/routes/coreRoutes/incomeApi.js
  serverside/src/services/checkBank.js
  serverside/src/services/checkMainAndSubHeadOfAccount.js
  serverside/src/services/createBankLedger.js
  serverside/src/services/createCashBookLedger.js
  serverside/src/services/createGeneralLedger.js
  serverside/src/services/generateVoucherNo.js
  serverside/src/services/updateIncomeLedger.js
  serverside/src/utils/generateRandomNumber.js
  serverside/src/utils/sendEmail.js
Labels: enhancement

#123 OE-35 | Backend | Scripts
  serverside/index.js
  serverside/src/controllers/scriptController/createIncomeHeadOfAccount.js
  serverside/src/controllers/scriptController/createMainExpenseHeadOfAccount.js
  serverside/src/controllers/scriptController/createSubExpenseHeadOfAccount.js
  serverside/src/controllers/scriptController/createTypeOfIncomeHeadOfAccount.js
  serverside/src/routes/scriptRoutes/script.js
Labels: enhancement

#124 OE-35 | Backend | Scripts Bug Fix
  serverside/src/controllers/scriptController/createIncomeHeadOfAccount.js
Labels: bug fix

#125 OE-10 | Frontend Bank Profit show balance in table
  officeErpFrontend/src/views/Banks/index.jsx
Labels: enhancement

#129 OE-10 | Frontend Bank Profit bank name abbreviation validation
  officeErpFrontend/src/views/Banks/index.jsx
Labels: enhancement

#130 OE-35 | Backend Scripts | Create Admin Script
  serverside/.env.template
  serverside/index.js
  serverside/src/controllers/userController/create.js
  serverside/src/models/coreModels/Admin.js
  serverside/src/models/scriptFlag/scriptFlag.js
  serverside/src/scripts/createAdmin.js
Labels: feature

#131 OE-36 | Backend | Bug Fixes
  serverside/src/controllers/fixedAmountController/fixedAmount.js
  serverside/src/models/expenseModel/auditFeeExpense/auditFeeExpense.js
  serverside/src/models/expenseModel/bankChargesExpense/bankChargesExpense.js
  serverside/src/models/expenseModel/electricityAndWaterConnectionExpense/electricityAndWaterConnectionExpense.js
  serverside/src/models/expenseModel/legalProfessionalExpense/legalProfessionalExpense.js
  serverside/src/models/expenseModel/miscellaneousExpense/miscellaneousExpense.js
  serverside/src/models/expenseModel/officeExpense/officeExpense.js
  serverside/src/models/expenseModel/officeUtilExpense/officeutilExpense.js
  serverside/src/models/expenseModel/salaries/salaries.js
  serverside/src/models/expenseModel/siteExpense/siteExpense.js
  serverside/src/models/fixedAmountModel/fixedAmount.js
  serverside/src/models/incomeModels/bankProfitModels/bankProfit.js
  serverside/src/models/incomeModels/pssessionFeeModel/possessionFee.js
  serverside/src/models/incomeModels/sellerPurchaseIncome/sellerPurchaseIncome.js
  serverside/src/models/ledgerModels/bankLedger.js
  serverside/src/models/ledgerModels/generalLedger.js
  serverside/src/models/memberModels/memberDeposit.js
  serverside/src/models/payableVoucherModel/payableVouchers.js
Labels: enhancement, bug fix

#132 OE-38 | Backend | Code Refactor | Database Optimization | Operating Fixed Assets
  serverside/index.js
  serverside/src/config/userPermissions.js
  serverside/src/controllers/incomeController/sellerPurchaseIncome.js
  serverside/src/controllers/operatingFixedAssetsController/operatingFixedAssets.js
  serverside/src/models/fixedAmountModel/fixedAmount.js
  serverside/src/models/operatingFixedAssetsModels/operatingFixedAssets.js
  serverside/src/routes/coreRoutes/coreApi.js
  serverside/src/routes/operatingFixedAssetsRoutes/operatingFixedAssets.js
Labels: enhancement, bug fix

#136 OE-3 | Backend | Code Refactor | Database Optimization | Operating Fixed Assets
  serverside/src/controllers/memberController/member.js
  serverside/src/controllers/userController/create.js
Labels: enhancement, bug fix

#137 OE-1 | Backend Code Refactor | Create Admin Fix
  serverside/src/controllers/userController/create.js
Labels: bug fix

#138 OE-40 | Frontend Transfer Membership
  officeErpFrontend/src/components/components/dynamic-sheet.tsx
  officeErpFrontend/src/services/members.js
  officeErpFrontend/src/views/Members/index.jsx
  officeErpFrontend/src/views/TransferIncome/index.jsx
Labels: feature

#140 OE-36 | Backend | Bug Fixes
  serverside/src/config/userPermissions.js
Labels: enhancement, bug fix

#139 OE-41 | Frontend Delisted Members
  officeErpFrontend/src/components/components/app-sidebar.tsx
  officeErpFrontend/src/routes/routes.jsx
  officeErpFrontend/src/services/members.js
  officeErpFrontend/src/views/DelistedMembers/index.jsx
  officeErpFrontend/src/views/index.jsx
Labels: feature

#141 OE-36 | Backend | Bug Fixes
  serverside/src/controllers/memberController/member.js
Labels: bug fix
