Repository computingfuturetech/officeERP, pull requests merged in 2025-01, with the labels that each got.

#70 OE-3 | Backend | Code Refactor | Database Optimization | BANK_LIST
  serverside/index.js
  serverside/src/controllers/bankController/bank.js
  serverside/src/controllers/bankController/bankBalance.js
  serverside/src/controllers/bankController/bankList.js
  serverside/src/controllers/bankController/createBank.js
  serverside/src/controllers/bankController/createBankBalance.js
  serverside/src/middleware/checkBank.js
  serverside/src/models/bankModel/bank.js
  serverside/src/models/bankModel/bankBalance.js
  serverside/src/routes/bankBalanceRoutes/bankBalance.js
  serverside/src/routes/bankRoutes/bank.js
  serverside/src/routes/coreRoutes/coreApi.js
Labels: bug, enhancement

#72 OE-5 | Backend | Code Refactor | Database Optimization | BANK_CHARGES_EXPENSE
  serverside/index.js
  serverside/src/controllers/expenseController/bankChargesExpense.js
  serverside/src/middleware/checkMainAndSubHeadOfAccount.js
  serverside/src/middleware/generateVoucherNo.js
  serverside/src/routes/bankChargesExpenseRoutes/bankChargesExpense.js
Labels: bug, enhancement

#74 OE-8 | Frontend | Authentication
  officeErpFrontend/src/components/components/app-sidebar.tsx
  officeErpFrontend/src/components/components/login-form.jsx
  officeErpFrontend/src/components/components/protected-route.tsx
  officeErpFrontend/src/core/api.js
  officeErpFrontend/src/layout/index.jsx
  officeErpFrontend/src/redux/user/user.js
  officeErpFrontend/src/routes/routes.jsx
  officeErpFrontend/src/services/authentication.js
  officeErpFrontend/src/views/LoginPage/index.jsx
Labels: enhancement

#75 OE-6 | Backend | Code Refactor | Database Optimization | MEMBER
  serverside/index.js
  serverside/package-lock.json
  serverside/package.json
  serverside/src/controllers/memberController/getDelistedMemberList.js
  serverside/src/controllers/memberController/getMemberList.js
  serverside/src/controllers/memberController/member.js
  serverside/src/controllers/memberController/memberDeposit.js
  serverside/src/controllers/memberController/newMember.js
  serverside/src/controllers/memberController/transferMembership.js
  serverside/src/controllers/memberController/updateMember.js
  serverside/src/models/ledgerModels/cashBookLedger.js
  serverside/src/models/ledgerModels/generalLedger.js
  serverside/src/models/memberModels/delistedMember.js
  serverside/src/models/memberModels/memberDeposit.js
  serverside/src/models/memberModels/memberList.js
  serverside/src/routes/coreRoutes/memberApi.js
  serverside/src/routes/memberRoutes/member.js
Labels: bug, enhancement

#77 OE-9 | Backend | Code Refactor | Database Optimization | BANK_PROFIT
  serverside/index.js
  serverside/src/controllers/incomeController/bankProfit.js
  serverside/src/middleware/createBankLedger.js
  serverside/src/middleware/createGeneralLedger.js
  serverside/src/middleware/generateVoucherNo.js
  serverside/src/models/incomeModels/bankProfitModels/bankProfit.js
  serverside/src/routes/bankProfitRoutes/bankProfit.js
  serverside/src/routes/coreRoutes/incomeApi.js
Labels: bug, bug fix

#79 OE-11 | Backend | Code Refactor | Database Optimization | WATER_MAINTENANCE
  serverside/index.js
  serverside/src/controllers/incomeController/bankProfit.js
  serverside/src/controllers/incomeController/waterMaintenanceBill.js
  serverside/src/middleware/checkMainAndSubHeadOfAccount.js
  serverside/src/middleware/createCashBookLedger.js
  serverside/src/models/incomeModels/waterMaintenanceBillModel/waterMaintenanceBill.js
  serverside/src/routes/coreRoutes/incomeApi.js
  serverside/src/routes/waterMaintenanceBillRoutes/waterMaintenanceBill.js
Labels: bug, enhancement, bug fix

#80 OE-13 | Backend | Code Refactor | Database Optimization | SELLER_PURC…
  serverside/src/controllers/incomeController/sellerPurchaseIncome.js
  serverside/src/models/incomeModels/sellerPurchaseIncome/sellerPurchaseIncome.js
Labels: bug, enhancement, bug fix

#81 OE-11 | Backend | Code Refactor | Database Optimization | WATER_MAINT…
  serverside/src/controllers/incomeController/waterMaintenanceBill.js
Labels: enhancement, bug fix

#83 OE-13 | Backend | Code Refactor | Database Optimization | SELLER_PURCHASER_INCOME
  serverside/index.js
  serverside/src/controllers/incomeController/sellerPurchaseIncome.js
  serverside/src/models/incomeModels/sellerPurchaseIncome/sellerPurchaseIncome.js
  serverside/src/routes/coreRoutes/incomeApi.js
  serverside/src/routes/sellerPurchaserRoutes/sellerPurchaser.js
Labels: enhancement, bug fix
